"""
预定义图标常量模块

包含 809 个来自 svglogo.top 的预定义图标映射。
每个图标可以通过其预定义名称在 show_system_notification() 中使用。

示例:
    show_system_notification("Hello", icon='claude')
    show_system_notification("Update ready", icon='github')
    show_system_notification("Processing", icon='deepseek')
"""

# 预定义图标映射 - 809 个图标
PREDEFINED_ICONS = {
	'11x': '11x.svg',  # 11x
	'302ai': '302AI.svg',  # 302AI
	'9air': '9Air.svg',  # 9Air
	'abc': 'ABC.svg',  # ABC
	'adbc': 'ADBC.svg',  # ADBC
	'adobefirefly': 'AdobeFirefly.svg',  # AdobeFirefly
	'agui': 'AGUI.svg',  # AGUI
	'ai21labs': 'Ai21Labs.svg',  # Ai21Labs
	'ai360': 'Ai360.svg',  # Ai360
	'aihubmix': 'AiHubMix.svg',  # AiHubMix
	'aimass': 'AiMass.svg',  # AiMass
	'aionlabs': 'AionLabs.svg',  # AionLabs
	'airchangan': 'AirChangan.svg',  # AirChangan
	'airchina': 'AirChina.svg',  # AirChina
	'airchinacargo': 'AirChinaCargo.svg',  # AirChinaCargo
	'airguilin': 'AirGuilin.svg',  # AirGuilin
	'airmacau': 'AirMacau.svg',  # AirMacau
	'airtravel': 'AirTravel.svg',  # AirTravel
	'aistudio': 'AIStudio.svg',  # AIStudio
	'alephalpha': 'AlephAlpha.svg',  # AlephAlpha
	'alipan': 'alipan.svg',  # alipan
	'aliyun': 'aliyun.svg',  # aliyun
	'anhuidaxue': 'AnHuiDaXue.svg',  # AnHuiDaXue
	'anhuixinhuauniversity': 'anhuiXinhuaUniversity.svg',  # anhuiXinhuaUniversity
	'antchan': 'Antchan.svg',  # Antchan
	'antforest': 'AntForest.svg',  # AntForest
	'antfoundation': 'AntFoundation.svg',  # AntFoundation
	'antgroup': 'AntGroup.svg',  # AntGroup
	'anthropic': 'Anthropic.svg',  # Anthropic
	'anyscale': 'Anyscale.svg',  # Anyscale
	'api': 'API.svg',  # API
	'applepodcast': 'applePodcast.svg',  # applePodcast
	'armanicaizhuang': 'ArmaniCaiZhuang.svg',  # ArmaniCaiZhuang
	'assemblyai': 'AssemblyAI.svg',  # AssemblyAI
	'aupres': 'aupres.svg',  # aupres
	'automatic1111': 'Automatic1111.svg',  # Automatic1111
	'avene': 'avene.svg',  # avene
	'aya': 'Aya.svg',  # Aya
	'azureai': 'AzureAI.svg',  # AzureAI
	'baai': 'BAAI.svg',  # BAAI
	'baichuan': 'Baichuan.svg',  # Baichuan
	'baidu': 'baidu.svg',  # baidu
	'baiducloud': 'BaiduCloud.svg',  # BaiduCloud
	'baiducould': 'baiducould.svg',  # baiducould
	'baseten': 'Baseten.svg',  # Baseten
	'bccb': 'BCCB.svg',  # BCCB
	'bedrockaws': 'BedrockAWS.svg',  # BedrockAWS
	'beihua_university': 'Beihua_University.svg',  # Beihua_University
	'beijinggongyedaxue': 'BeiJingGongYeDaXue.svg',  # BeiJingGongYeDaXue
	'beijingjiaotongdaxue': 'BeiJingJiaoTongDaXue.svg',  # BeiJingJiaoTongDaXue
	'beijingligongdaxue': 'BeiJingLiGongDaXue.svg',  # BeiJingLiGongDaXue
	'beijinglinyedaxue': 'BeiJingLinYeDaXue.svg',  # BeiJingLinYeDaXue
	'beijingshifandaxue': 'BeiJingShiFanDaXue.svg',  # BeiJingShiFanDaXue
	'beijingwaiguoyudaxue': 'BeiJingWaiGuoYuDaXue.svg',  # BeiJingWaiGuoYuDaXue
	'bgb': 'BGB.svg',  # BGB
	'bhb': 'BHB.svg',  # BHB
	'bilibili': 'bilibili.svg',  # bilibili
	'bing': 'Bing.svg',  # Bing
	'biotherm': 'biotherm.svg',  # biotherm
	'boardmix': 'boardmix.svg',  # boardmix
	'boas': 'BOAS.svg',  # BOAS
	'bob': 'BOB.svg',  # BOB
	'bobbibrown': 'bobbibrown.svg',  # bobbibrown
	'bobd': 'BOBD.svg',  # BOBD
	'boc': 'BOC.svg',  # BOC
	'bocy': 'BOCY.svg',  # BOCY
	'bocz': 'BOCZ.svg',  # BOCZ
	'bod': 'BOD.svg',  # BOD
	'bodd': 'BODD.svg',  # BODD
	'bogs': 'BOGS.svg',  # BOGS
	'bogz': 'BOGZ.svg',  # BOGZ
	'bohaib': 'BOHAIB.svg',  # BOHAIB
	'bohld': 'BOHLD.svg',  # BOHLD
	'bohs': 'BOHS.svg',  # BOHS
	'bohz': 'BOHZ.svg',  # BOHZ
	'bojl': 'BOJL.svg',  # BOJL
	'bolf': 'BOLF.svg',  # BOLF
	'boly': 'BOLY.svg',  # BOLY
	'bop': 'BOP.svg',  # BOP
	'bopj': 'BOPJ.svg',  # BOPJ
	'boqz': 'BOQZ.svg',  # BOQZ
	'bosc': 'BOSC.svg',  # BOSC
	'bosz': 'BOSZ.svg',  # BOSZ
	'botj': 'BOTJ.svg',  # BOTJ
	'botl': 'BOTL.svg',  # BOTL
	'bots': 'BOTS.svg',  # BOTS
	'boxz': 'BOXZ.svg',  # BOXZ
	'boyk': 'BOYK.svg',  # BOYK
	'bscb': 'BSCB.svg',  # BSCB
	'bsu': 'BSU.svg',  # BSU
	'buaa': 'BUAA.svg',  # BUAA
	'bucm': 'BUCM.svg',  # BUCM
	'buct': 'BUCT.svg',  # BUCT
	'bupt': 'BUPT.svg',  # BUPT
	'burncloud': 'BurnCloud.svg',  # BurnCloud
	'bytedance': 'bytedance.svg',  # bytedance
	'caa': 'CAA.svg',  # CAA
	'cabank': 'CABANK.svg',  # CABANK
	'cafa_wordmark': 'CAFA_wordmark.svg',  # CAFA_wordmark
	'caiyunapp': 'caiyunapp.svg',  # caiyunapp
	'canva': 'Canva.svg',  # Canva
	'capitalairlines': 'CapitalAirlines.svg',  # CapitalAirlines
	'cathaypacific': 'CathayPacific.svg',  # CathayPacific
	'cau': 'CAU.svg',  # CAU
	'ccb': 'CCB.svg',  # CCB
	'ccnu': 'CCNU.svg',  # CCNU
	'ccom': 'CCOM.svg',  # CCOM
	'ccqtgb': 'CCQTGB.svg',  # CCQTGB
	'cdb': 'CDB.svg',  # CDB
	'cdbank': 'CDBANK.svg',  # CDBANK
	'cdcb': 'CDCB.svg',  # CDCB
	'cdut': 'CDUT.svg',  # CDUT
	'ceb': 'CEB.svg',  # CEB
	'centml': 'CentML.svg',  # CentML
	'cerebras': 'Cerebras.svg',  # Cerebras
	'cfau': 'CFAU.svg',  # CFAU
	'chanel': 'chanel.svg',  # chanel
	'chaohongji': 'chaohongji.svg',  # chaohongji
	'chatglm': 'ChatGLM.svg',  # ChatGLM
	'chengduairlines': 'CHENGDUAIRLINES.svg',  # CHENGDUAIRLINES
	'chinaairlines_wordmark': 'ChinaAirlines_wordmark.svg',  # ChinaAirlines_wordmark
	'chinaeasternairlines': 'ChinaEasternAirlines.svg',  # ChinaEasternAirlines
	'chinaexpress': 'ChinaExpress.svg',  # ChinaExpress
	'chinalife': 'chinaLife.svg',  # chinaLife
	'chinamobile': 'chinaMobile.svg',  # chinaMobile
	'chinapostalairlines_wordmark': 'ChinaPostalAirlines_wordmark.svg',  # ChinaPostalAirlines_wordmark
	'chinasouthernairlines': 'ChinaSouthernAirlines.svg',  # ChinaSouthernAirlines
	'chinatelecom': 'chinatelecom.svg',  # chinatelecom
	'chinaunicom': 'chinaunicom.svg',  # chinaunicom
	'chinaunitedairlines': 'ChinaUnitedAirlines.svg',  # ChinaUnitedAirlines
	'chongqingairlines': 'ChongqingAirlines.svg',  # ChongqingAirlines
	'chu': 'CHU.svg',  # CHU
	'cib': 'CIB.svg',  # CIB
	'citic': 'CITIC.svg',  # CITIC
	'civitai': 'Civitai.svg',  # Civitai
	'clarins': 'Clarins.svg',  # Clarins
	'claude': 'claude.svg',  # claude
	'cledepeau': 'cledepeau.svg',  # cledepeau
	'cline': 'Cline.svg',  # Cline
	'clipdrop': 'Clipdrop.svg',  # Clipdrop
	'cloudflare': 'Cloudflare.svg',  # Cloudflare
	'cmb': 'CMB.svg',  # CMB
	'cmbc': 'CMBC.svg',  # CMBC
	'cnu': 'CNU.svg',  # CNU
	'codegeex': 'CodeGeeX.svg',  # CodeGeeX
	'cogvideo': 'CogVideo.svg',  # CogVideo
	'cogview': 'CogView.svg',  # CogView
	'cohere': 'Cohere.svg',  # Cohere
	'colab': 'Colab.svg',  # Colab
	'cold_blue': 'cold_blue.svg',  # cold_blue
	'cold_orange': 'cold_orange.svg',  # cold_orange
	'cold_red': 'cold_red.svg',  # cold_red
	'cold_yellow': 'cold_yellow.svg',  # cold_yellow
	'coldinjury_blue': 'coldInjury_blue.svg',  # coldInjury_blue
	'coldinjury_orange': 'coldInjury_orange.svg',  # coldInjury_orange
	'coldinjury_red': 'coldInjury_red.svg',  # coldInjury_red
	'coldinjury_yellow': 'coldInjury_yellow.svg',  # coldInjury_yellow
	'coldrainsnow_blue': 'coldRainSnow_blue.svg',  # coldRainSnow_blue
	'coldrainsnow_orange': 'coldRainSnow_orange.svg',  # coldRainSnow_orange
	'coldrainsnow_red': 'coldRainSnow_red.svg',  # coldRainSnow_red
	'coldrainsnow_yellow': 'coldRainSnow_yellow.svg',  # coldRainSnow_yellow
	'coldspell_blue': 'coldSpell_blue.svg',  # coldSpell_blue
	'coldspell_orange': 'coldSpell_orange.svg',  # coldSpell_orange
	'coldspell_red': 'coldSpell_red.svg',  # coldSpell_red
	'coldspell_yellow': 'coldSpell_yellow.svg',  # coldSpell_yellow
	'coldwave_blue': 'coldWave_blue.svg',  # coldWave_blue
	'coldwave_orange': 'coldWave_orange.svg',  # coldWave_orange
	'coldwave_red': 'coldWave_red.svg',  # coldWave_red
	'coldwave_yellow': 'coldWave_yellow.svg',  # coldWave_yellow
	'colorfulguizhouairlines': 'ColorfulGuizhouAirlines.svg',  # ColorfulGuizhouAirlines
	'comfyui': 'ComfyUI.svg',  # ComfyUI
	'comm': 'COMM.svg',  # COMM
	'cooling_blue': 'cooling_blue.svg',  # cooling_blue
	'cooling_orange': 'cooling_orange.svg',  # cooling_orange
	'cooling_red': 'cooling_red.svg',  # cooling_red
	'cooling_yellow': 'cooling_yellow.svg',  # cooling_yellow
	'copilotkit': 'CopilotKit.svg',  # CopilotKit
	'coqui': 'Coqui.svg',  # Coqui
	'cosmoplat_wordmark': 'cosmoplat_wordmark.svg',  # cosmoplat_wordmark
	'coze': 'Coze.svg',  # Coze
	'cqbank': 'CQBANK.svg',  # CQBANK
	'cqu': 'CQU.svg',  # CQU
	'crewai': 'CrewAI.svg',  # CrewAI
	'crusoe': 'Crusoe.svg',  # Crusoe
	'csu': 'CSU.svg',  # CSU
	'cts': 'CTS.svg',  # CTS
	'cuc': 'CUC.svg',  # CUC
	'cufe': 'CUFE.svg',  # CUFE
	'cug': 'CUG.svg',  # CUG
	'cup': 'CUP.svg',  # CUP
	'cursor': 'Cursor.svg',  # Cursor
	'czb': 'CZB.svg',  # CZB
	'czbank': 'CZBANK.svg',  # CZBANK
	'czcb': 'CZCB.svg',  # CZCB
	'dalianairlines': 'DalianAirlines.svg',  # DalianAirlines
	'dall%c2%b7e': 'DALL%C2%B7E.svg',  # DALL%C2%B7E
	'darryring': 'darryring.svg',  # darryring
	'dbrx': 'DBRX.svg',  # DBRX
	'dccb': 'DCCB.svg',  # DCCB
	'deepai': 'DeepAI.svg',  # DeepAI
	'deepinfra': 'DeepInfra.svg',  # DeepInfra
	'deepmind': 'DeepMind.svg',  # DeepMind
	'deepseek': 'deepseek.svg',  # deepseek
	'densedust_blue': 'denseDust_blue.svg',  # denseDust_blue
	'densedust_orange': 'denseDust_orange.svg',  # denseDust_orange
	'densedust_red': 'denseDust_red.svg',  # denseDust_red
	'densedust_yellow': 'denseDust_yellow.svg',  # denseDust_yellow
	'dhwind_blue': 'dhWind_blue.svg',  # dhWind_blue
	'dhwind_orange': 'dhWind_orange.svg',  # dhWind_orange
	'dhwind_red': 'dhWind_red.svg',  # dhWind_red
	'dhwind_yellow': 'dhWind_yellow.svg',  # dhWind_yellow
	'dify': 'Dify.svg',  # Dify
	'dingding': 'dingDing.svg',  # dingDing
	'dior': 'dior.svg',  # dior
	'dlb': 'DLB.svg',  # DLB
	'doc2x': 'Doc2X.svg',  # Doc2X
	'docsearch': 'DocSearch.svg',  # DocSearch
	'donghaiairlines': 'DonghaiAirlines.svg',  # DonghaiAirlines
	'dongqiudi': 'dongqiudi.svg',  # dongqiudi
	'douban': 'douBan.svg',  # douBan
	'doubao': 'Doubao.svg',  # Doubao
	'douyin': 'douYin.svg',  # douYin
	'douyu': 'douYu.svg',  # douYu
	'dreammachine': 'DreamMachine.svg',  # DreamMachine
	'dribbble': 'dribbble.svg',  # dribbble
	'drought_blue': 'drought_blue.svg',  # drought_blue
	'drought_orange': 'drought_orange.svg',  # drought_orange
	'drought_red': 'drought_red.svg',  # drought_red
	'drought_yellow': 'drought_yellow.svg',  # drought_yellow
	'dtb': 'DTB.svg',  # DTB
	'dust_blue': 'dust_blue.svg',  # dust_blue
	'dust_orange': 'dust_orange.svg',  # dust_orange
	'dust_red': 'dust_red.svg',  # dust_red
	'dust_yellow': 'dust_yellow.svg',  # dust_yellow
	'dut': 'DUT.svg',  # DUT
	'dyccb': 'DYCCB.svg',  # DYCCB
	'dzbank': 'DZBANK.svg',  # DZBANK
	'ecnu': 'ECNU.svg',  # ECNU
	'egbank': 'EGBANK.svg',  # EGBANK
	'eibof': 'EIBOF.svg',  # EIBOF
	'elevenlabs': 'ElevenLabs.svg',  # ElevenLabs
	'esteelauder': 'esteelauder.svg',  # esteelauder
	'evaairways': 'EVAAirways.svg',  # EVAAirways
	'exa': 'Exa.svg',  # Exa
	'excel': 'excel.svg',  # excel
	'fal': 'Fal.svg',  # Fal
	'fankehudong': 'fankehudong.svg',  # fankehudong
	'fanwenhua': 'fanwenhua.svg',  # fanwenhua
	'fastgpt': 'FastGPT.svg',  # FastGPT
	'fdbank': 'FDBANK.svg',  # FDBANK
	'fdu': 'FDU.svg',  # FDU
	'featherlessai': 'FeatherlessAI.svg',  # FeatherlessAI
	'feishu': 'feiShu.svg',  # feiShu
	'fireworks': 'Fireworks.svg',  # Fireworks
	'fishaudio': 'FishAudio.svg',  # FishAudio
	'fjhxbc': 'FJHXBC.svg',  # FJHXBC
	'fjnu': 'FJNU.svg',  # FJNU
	'fjut': 'FJUT.svg',  # FJUT
	'flora': 'Flora.svg',  # Flora
	'flowith': 'Flowith.svg',  # Flowith
	'flux': 'Flux.svg',  # Flux
	'friendli': 'Friendli.svg',  # Friendli
	'frost_blue': 'frost_blue.svg',  # frost_blue
	'frost_orange': 'frost_orange.svg',  # frost_orange
	'frost_red': 'frost_red.svg',  # frost_red
	'frost_yellow': 'frost_yellow.svg',  # frost_yellow
	'frozen_blue': 'frozen_blue.svg',  # frozen_blue
	'frozen_orange': 'frozen_orange.svg',  # frozen_orange
	'frozen_red': 'frozen_red.svg',  # frozen_red
	'frozen_yellow': 'frozen_yellow.svg',  # frozen_yellow
	'fscb': 'FSCB.svg',  # FSCB
	'fuzhouairlines': 'FuzhouAirlines.svg',  # FuzhouAirlines
	'fxcb': 'FXCB.svg',  # FXCB
	'fzu': 'FZU.svg',  # FZU
	'gale_blue': 'gale_blue.svg',  # gale_blue
	'gale_orange': 'gale_orange.svg',  # gale_orange
	'gale_red': 'gale_red.svg',  # gale_red
	'gale_yellow': 'gale_yellow.svg',  # gale_yellow
	'garsslandfirerisk_blue': 'garsslandFireRisk_blue.svg',  # garsslandFireRisk_blue
	'garsslandfirerisk_orange': 'garsslandFireRisk_orange.svg',  # garsslandFireRisk_orange
	'garsslandfirerisk_red': 'garsslandFireRisk_red.svg',  # garsslandFireRisk_red
	'garsslandfirerisk_yellow': 'garsslandFireRisk_yellow.svg',  # garsslandFireRisk_yellow
	'gdb': 'GDB.svg',  # GDB
	'gemini': 'Gemini.svg',  # Gemini
	'gemma': 'Gemma.svg',  # Gemma
	'genghiskhanairlines': 'GenghisKhanAirlines.svg',  # GenghisKhanAirlines
	'geologicalhazad_blue': 'geologicalHazad_blue.svg',  # geologicalHazad_blue
	'geologicalhazad_orange': 'geologicalHazad_orange.svg',  # geologicalHazad_orange
	'geologicalhazad_red': 'geologicalHazad_red.svg',  # geologicalHazad_red
	'geologicalhazad_yellow': 'geologicalHazad_yellow.svg',  # geologicalHazad_yellow
	'ghb': 'GHB.svg',  # GHB
	'giteeai': 'GiteeAI.svg',  # GiteeAI
	'github': 'github.svg',  # github
	'githubcopilot': 'GithubCopilot.svg',  # GithubCopilot
	'givenchy': 'givenchy.svg',  # givenchy
	'glama': 'Glama.svg',  # Glama
	'glbank': 'GLBANK.svg',  # GLBANK
	'glif': 'Glif.svg',  # Glif
	'gongzhonghao': 'gongZhongHao.svg',  # gongZhongHao
	'goose': 'Goose.svg',  # Goose
	'gradio': 'Gradio.svg',  # Gradio
	'grandchinaair': 'GrandChinaAir.svg',  # GrandChinaAir
	'greaterbayairlines': 'GreaterBayAirlines.svg',  # GreaterBayAirlines
	'greptile': 'Greptile.svg',  # Greptile
	'grok': 'Grok.svg',  # Grok
	'groq': 'Groq.svg',  # Groq
	'guerlain': 'guerlain.svg',  # guerlain
	'gwb': 'GWB.svg',  # GWB
	'gxairlines': 'GXAirlines.svg',  # GXAirlines
	'gxu': 'GXU.svg',  # GXU
	'gyccb': 'GYCCB.svg',  # GYCCB
	'gzcb': 'GZCB.svg',  # GZCB
	'gznu': 'GZNU.svg',  # GZNU
	'gzu': 'GZU.svg',  # GZU
	'gzucm': 'GZUCM.svg',  # GZUCM
	'h3cb': 'H3CB.svg',  # H3CB
	'hailuo': 'Hailuo.svg',  # Hailuo
	'hainanairlines': 'HainanAirlines.svg',  # HainanAirlines
	'haiper': 'Haiper.svg',  # Haiper
	'haut_wordmark': 'HAUT_wordmark.svg',  # HAUT_wordmark
	'haze_blue': 'haze_blue.svg',  # haze_blue
	'haze_orange': 'haze_orange.svg',  # haze_orange
	'haze_red': 'haze_red.svg',  # haze_red
	'haze_yellow': 'haze_yellow.svg',  # haze_yellow
	'hbc': 'HBC.svg',  # HBC
	'hbucm': 'HBUCM.svg',  # HBUCM
	'hdbank': 'HDBANK.svg',  # HDBANK
	'heatwave_blue': 'heatWave_blue.svg',  # heatWave_blue
	'heatwave_orange': 'heatWave_orange.svg',  # heatWave_orange
	'heatwave_red': 'heatWave_red.svg',  # heatWave_red
	'heatwave_yellow': 'heatWave_yellow.svg',  # heatWave_yellow
	'heavyfog_blue': 'heavyFog_blue.svg',  # heavyFog_blue
	'heavyfog_orange': 'heavyFog_orange.svg',  # heavyFog_orange
	'heavyfog_red': 'heavyFog_red.svg',  # heavyFog_red
	'heavyfog_yellow': 'heavyFog_yellow.svg',  # heavyFog_yellow
	'heavypollution_blue': 'heavyPollution_blue.svg',  # heavyPollution_blue
	'heavypollution_orange': 'heavyPollution_orange.svg',  # heavyPollution_orange
	'heavypollution_red': 'heavyPollution_red.svg',  # heavyPollution_red
	'heavypollution_yellow': 'heavyPollution_yellow.svg',  # heavyPollution_yellow
	'heavyrainfall_blue': 'heavyRainfall_blue.svg',  # heavyRainfall_blue
	'heavyrainfall_orange': 'heavyRainfall_orange.svg',  # heavyRainfall_orange
	'heavyrainfall_red': 'heavyRainfall_red.svg',  # heavyRainfall_red
	'heavyrainfall_yellow': 'heavyRainfall_yellow.svg',  # heavyRainfall_yellow
	'heavysnow_blue': 'heavySnow_blue.svg',  # heavySnow_blue
	'heavysnow_orange': 'heavySnow_orange.svg',  # heavySnow_orange
	'heavysnow_red': 'heavySnow_red.svg',  # heavySnow_red
	'heavysnow_yellow': 'heavySnow_yellow.svg',  # heavySnow_yellow
	'hebeiairlines': 'HebeiAirlines.svg',  # HebeiAirlines
	'hedra': 'Hedra.svg',  # Hedra
	'helenarubinstein': 'HelenaRubinstein.svg',  # HelenaRubinstein
	'henangongchengxueyuan': 'HeNanGongChengXueYuan.svg',  # HeNanGongChengXueYuan
	'hfut': 'HFUT.svg',  # HFUT
	'hfuu': 'HFUU.svg',  # HFUU
	'higress': 'Higress.svg',  # Higress
	'hit': 'HIT.svg',  # HIT
	'hkb': 'HKB.svg',  # HKB
	'hkexpress': 'HKExpress.svg',  # HKExpress
	'hmccb': 'HMCCB.svg',  # HMCCB
	'hnb': 'HNB.svg',  # HNB
	'hnnu': 'HNNU.svg',  # HNNU
	'hnu': 'HNU.svg',  # HNU
	'hongkongairlines': 'HongKongAirlines.svg',  # HongKongAirlines
	'hrbcb': 'HRBCB.svg',  # HRBCB
	'hrxjb': 'HRXJB.svg',  # HRXJB
	'hsbank': 'HSBANK.svg',  # HSBANK
	'huabei': 'huabei.svg',  # huabei
	'huawei': 'huawei.svg',  # huawei
	'huazai': 'huazai.svg',  # huazai
	'hubu': 'HUBU.svg',  # HUBU
	'huggingface': 'HuggingFace.svg',  # HuggingFace
	'hunyuan': 'Hunyuan.svg',  # Hunyuan
	'hupu': 'huPu.svg',  # huPu
	'hust': 'HUST.svg',  # HUST
	'huya': 'huYa.svg',  # huYa
	'hxb': 'HXB.svg',  # HXB
	'hyperbolic': 'Hyperbolic.svg',  # Hyperbolic
	'hzau': 'HZAU.svg',  # HZAU
	'hzcb': 'HZCB.svg',  # HZCB
	'icbc': 'ICBC.svg',  # ICBC
	'iconfont': 'iconfont.svg',  # iconfont
	'ideogram': 'Ideogram.svg',  # Ideogram
	'iflytekcloud': 'IFlyTekCloud.svg',  # IFlyTekCloud
	'inference': 'Inference.svg',  # Inference
	'infermatic': 'Infermatic.svg',  # Infermatic
	'infinigence': 'Infinigence.svg',  # Infinigence
	'inflection': 'Inflection.svg',  # Inflection
	'innisfree': 'Innisfree.svg',  # Innisfree
	'inspur': 'inspur.svg',  # inspur
	'internlm': 'InternLM.svg',  # InternLM
	'ipsa': 'ipsa.svg',  # ipsa
	'jdt': 'JDT.svg',  # JDT
	'jhccb': 'JHCCB.svg',  # JHCCB
	'jiangxiair': 'JiangxiAir.svg',  # JiangxiAir
	'jiebei': 'jiebei.svg',  # jiebei
	'jike': 'jike.svg',  # jike
	'jimeng': 'Jimeng.svg',  # Jimeng
	'jinaai': 'JinaAI.svg',  # JinaAI
	'jinandaxue': 'JiNanDaXue.svg',  # JiNanDaXue
	'jinchb': 'JINCHB.svg',  # JINCHB
	'jinritoutiao': 'jinRiTouTiao.svg',  # jinRiTouTiao
	'jjccb': 'JJCCB.svg',  # JJCCB
	'jlu': 'JLU.svg',  # JLU
	'jnbank': 'JNBANK.svg',  # JNBANK
	'jnu': 'JNU.svg',  # JNU
	'joyair': 'JoyAir.svg',  # JoyAir
	'jsb': 'JSB.svg',  # JSB
	'jsbank': 'JSBANK.svg',  # JSBANK
	'jscjcb': 'JSCJCB.svg',  # JSCJCB
	'jsdesign': 'jsdesign.svg',  # jsdesign
	'juneyaoair': 'JuneyaoAir.svg',  # JuneyaoAir
	'jurlique': 'Jurlique.svg',  # Jurlique
	'jxb': 'JXB.svg',  # JXB
	'jxbank': 'JXBANK.svg',  # JXBANK
	'jxnu': 'JXNU.svg',  # JXNU
	'jzb': 'JZB.svg',  # JZB
	'jzbank': 'JZBANK.svg',  # JZBANK
	'kamyangtechnology': 'KamyangTechnology.svg',  # KamyangTechnology
	'kcccb': 'KCCCB.svg',  # KCCCB
	'keep': 'keep.svg',  # keep
	'kera': 'Kera.svg',  # Kera
	'kiehls': 'kiehls.svg',  # kiehls
	'kimi': 'Kimi.svg',  # Kimi
	'klb': 'KLB.svg',  # KLB
	'kling': 'Kling.svg',  # Kling
	'kuaishou': 'kuaiShou.svg',  # kuaiShou
	'kunmingairlines': 'KunmingAirlines.svg',  # KunmingAirlines
	'lamer': 'lamer.svg',  # lamer
	'lancome': 'lancome.svg',  # lancome
	'laneige': 'laneige.svg',  # laneige
	'laofengxiang': 'laofengxiang.svg',  # laofengxiang
	'laomiao': 'laomiao.svg',  # laomiao
	'lightning_blue': 'lightning_blue.svg',  # lightning_blue
	'lightning_orange': 'lightning_orange.svg',  # lightning_orange
	'lightning_red': 'lightning_red.svg',  # lightning_red
	'lightning_yellow': 'lightning_yellow.svg',  # lightning_yellow
	'lightninggale_blue': 'lightningGale_blue.svg',  # lightningGale_blue
	'lightninggale_orange': 'lightningGale_orange.svg',  # lightningGale_orange
	'lightninggale_red': 'lightningGale_red.svg',  # lightningGale_red
	'lightninggale_yellow': 'lightningGale_yellow.svg',  # lightningGale_yellow
	'lit': 'LIT.svg',  # LIT
	'liufuzhubao': 'liufuzhubao.svg',  # liufuzhubao
	'ljair': 'LJAir.svg',  # LJAir
	'ljbank': 'LJBANK.svg',  # LJBANK
	'loccitane': 'loccitane.svg',  # loccitane
	'lofter': 'lofter.svg',  # lofter
	'loongair': 'LoongAir.svg',  # LoongAir
	'loreal': 'loreal.svg',  # loreal
	'lsbank': 'LSBANK.svg',  # LSBANK
	'lsbc': 'LSBC.svg',  # LSBC
	'lsccb': 'LSCCB.svg',  # LSCCB
	'luckyair': 'LuckyAir.svg',  # LuckyAir
	'luma': 'Luma.svg',  # Luma
	'lzb': 'LZB.svg',  # LZB
	'lzbank': 'LZBANK.svg',  # LZBANK
	'lzccb': 'LZCCB.svg',  # LZCCB
	'lzu': 'LZU.svg',  # LZU
	'mac': 'mac.svg',  # mac
	'maimai': 'maiMai.svg',  # maiMai
	'makeupforever': 'makeupforever.svg',  # makeupforever
	'mamonde': 'mamonde.svg',  # mamonde
	'mandarinairlines': 'MandarinAirlines.svg',  # MandarinAirlines
	'maogeping': 'maogeping.svg',  # maogeping
	'marubi': 'marubi.svg',  # marubi
	'mastergo': 'masterGo.svg',  # masterGo
	'meta': 'Meta.svg',  # Meta
	'microsoftazure': 'MicrosoftAzure.svg',  # MicrosoftAzure
	'microsoftteams': 'MicrosoftTeams.svg',  # MicrosoftTeams
	'midjourney': 'Midjourney.svg',  # Midjourney
	'mingpaizhubao': 'mingpaizhubao.svg',  # mingpaizhubao
	'mistral': 'Mistral.svg',  # Mistral
	'modao': 'Modao.svg',  # Modao
	'moonvy': 'Moonvy.svg',  # Moonvy
	'motiff': 'Motiff.svg',  # Motiff
	'mountaintorrents_blue': 'mountainTorrents_blue.svg',  # mountainTorrents_blue
	'mountaintorrents_orange': 'mountainTorrents_orange.svg',  # mountainTorrents_orange
	'mountaintorrents_red': 'mountainTorrents_red.svg',  # mountainTorrents_red
	'mountaintorrents_yellow': 'mountainTorrents_yellow.svg',  # mountainTorrents_yellow
	'mtbank': 'MTBANK.svg',  # MTBANK
	'muc': 'MUC.svg',  # MUC
	'mybank': 'Mybank.svg',  # Mybank
	'myccb': 'MYCCB.svg',  # MYCCB
	'naixuedecha': 'NaiXueDeCha.svg',  # NaiXueDeCha
	'nbcb': 'NBCB.svg',  # NBCB
	'nbcmb': 'NBCMB.svg',  # NBCMB
	'nbu': 'NBU.svg',  # NBU
	'ndhb': 'NDHB.svg',  # NDHB
	'neu': 'NEU.svg',  # NEU
	'niutrans': 'niutrans.svg',  # niutrans
	'njcb': 'NJCB.svg',  # NJCB
	'njfu': 'NJFU.svg',  # NJFU
	'njnu': 'NJNU.svg',  # NJNU
	'nju': 'NJU.svg',  # NJU
	'njucm': 'NJUCM.svg',  # NJUCM
	'nku': 'NKU.svg',  # NKU
	'nudt': 'NUDT.svg',  # NUDT
	'nuist': 'NUIST.svg',  # NUIST
	'nwafu': 'NWAFU.svg',  # NWAFU
	'nwpu': 'NWPU.svg',  # NWPU
	'nwu': 'NWU.svg',  # NWU
	'nxbank': 'NXBANK.svg',  # NXBANK
	'nxu': 'NXU.svg',  # NXU
	'nybank': 'NYBANK.svg',  # NYBANK
	'okayairways': 'OkayAirways.svg',  # OkayAirways
	'olay': 'olay.svg',  # olay
	'ollama': 'Ollama.svg',  # Ollama
	'onenote': 'OneNote.svg',  # OneNote
	'openai': 'OpenAI.svg',  # OpenAI
	'openrouter': 'OpenRouter.svg',  # OpenRouter
	'ordosb': 'ORDOSB.svg',  # ORDOSB
	'origns': 'origns.svg',  # origns
	'other_blue': 'other_blue.svg',  # other_blue
	'other_orange': 'other_orange.svg',  # other_orange
	'other_red': 'other_red.svg',  # other_red
	'other_yellow': 'other_yellow.svg',  # other_yellow
	'ouc': 'OUC.svg',  # OUC
	'outlook': 'outlook.svg',  # outlook
	'ozone_blue': 'ozone_blue.svg',  # ozone_blue
	'ozone_orange': 'ozone_orange.svg',  # ozone_orange
	'ozone_red': 'ozone_red.svg',  # ozone_red
	'ozone_yellow': 'ozone_yellow.svg',  # ozone_yellow
	'pandora': 'pandora.svg',  # pandora
	'pboc': 'PBOC.svg',  # PBOC
	'perplexity': 'Perplexity.svg',  # Perplexity
	'pixso': 'Pixso.svg',  # Pixso
	'pku': 'PKU.svg',  # PKU
	'ppt': 'ppt.svg',  # ppt
	'proya': 'proya.svg',  # proya
	'psbc': 'PSBC.svg',  # PSBC
	'qdccb': 'QDCCB.svg',  # QDCCB
	'qhbank': 'QHBANK.svg',  # QHBANK
	'qhdbank': 'QHDBANK.svg',  # QHDBANK
	'qhu': 'QHU.svg',  # QHU
	'qingdaoairlines': 'QingdaoAirlines.svg',  # QingdaoAirlines
	'qingicon': 'qingicon.svg',  # qingicon
	'qingtingfm': 'qingTingFM.svg',  # qingTingFM
	'qiyeweixin': 'qiyeweixin.svg',  # qiyeweixin
	'qjcccb': 'QJCCCB.svg',  # QJCCCB
	'qlbank': 'QLBANK.svg',  # QLBANK
	'qq': 'QQ.svg',  # QQ
	'qsb': 'QSB.svg',  # QSB
	'quarkpan': 'quarkpan.svg',  # quarkpan
	'qut': 'QUT.svg',  # QUT
	'qwen': 'Qwen.svg',  # Qwen
	'rainstrom_blue': 'rainStrom_blue.svg',  # rainStrom_blue
	'rainstrom_orange': 'rainStrom_orange.svg',  # rainStrom_orange
	'rainstrom_red': 'rainStrom_red.svg',  # rainStrom_red
	'rainstrom_yellow': 'rainStrom_yellow.svg',  # rainStrom_yellow
	'rboz': 'RBOZ.svg',  # RBOZ
	'replicate': 'Replicate.svg',  # Replicate
	'roadicesnow_blue': 'roadIceSnow_blue.svg',  # roadIceSnow_blue
	'roadicesnow_orange': 'roadIceSnow_orange.svg',  # roadIceSnow_orange
	'roadicesnow_red': 'roadIceSnow_red.svg',  # roadIceSnow_red
	'roadicesnow_yellow': 'roadIceSnow_yellow.svg',  # roadIceSnow_yellow
	'roadicing_blue': 'roadIcing_blue.svg',  # roadIcing_blue
	'roadicing_orange': 'roadIcing_orange.svg',  # roadIcing_orange
	'roadicing_red': 'roadIcing_red.svg',  # roadIcing_red
	'roadicing_yellow': 'roadIcing_yellow.svg',  # roadIcing_yellow
	'ruc': 'RUC.svg',  # RUC
	'ruiliairlines': 'RuiliAirlines.svg',  # RuiliAirlines
	'runshishanhu': 'runshishanhu.svg',  # runshishanhu
	'runway': 'Runway.svg',  # Runway
	'rzb': 'RZB.svg',  # RZB
	'sandstrom_blue': 'sandStrom_blue.svg',  # sandStrom_blue
	'sandstrom_orange': 'sandStrom_orange.svg',  # sandStrom_orange
	'sandstrom_red': 'sandStrom_red.svg',  # sandStrom_red
	'sandstrom_yellow': 'sandStrom_yellow.svg',  # sandStrom_yellow
	'scb': 'SCB.svg',  # SCB
	'scmzu': 'SCMZU.svg',  # SCMZU
	'scnu': 'SCNU.svg',  # SCNU
	'sctfb': 'SCTFB.svg',  # SCTFB
	'scu': 'SCU.svg',  # SCU
	'scut': 'SCUT.svg',  # SCUT
	'sdu': 'SDU.svg',  # SDU
	'seafog_blue': 'seaFog_blue.svg',  # seaFog_blue
	'seafog_orange': 'seaFog_orange.svg',  # seaFog_orange
	'seafog_red': 'seaFog_red.svg',  # seaFog_red
	'seafog_yellow': 'seaFog_yellow.svg',  # seaFog_yellow
	'seagale_blue': 'seaGale_blue.svg',  # seaGale_blue
	'seagale_orange': 'seaGale_orange.svg',  # seaGale_orange
	'seagale_red': 'seaGale_red.svg',  # seaGale_red
	'seagale_yellow': 'seaGale_yellow.svg',  # seaGale_yellow
	'sealightning_blue': 'seaLightning_blue.svg',  # seaLightning_blue
	'sealightning_orange': 'seaLightning_orange.svg',  # seaLightning_orange
	'sealightning_red': 'seaLightning_red.svg',  # seaLightning_red
	'sealightning_yellow': 'seaLightning_yellow.svg',  # seaLightning_yellow
	'sealightninggale_blue': 'sealightningGale_blue.svg',  # sealightningGale_blue
	'sealightninggale_orange': 'sealightningGale_orange.svg',  # sealightningGale_orange
	'sealightninggale_red': 'sealightningGale_red.svg',  # sealightningGale_red
	'sealightninggale_yellow': 'sealightningGale_yellow.svg',  # sealightningGale_yellow
	'seatyphoon_blue': 'seaTyphoon_blue.svg',  # seaTyphoon_blue
	'seatyphoon_orange': 'seaTyphoon_orange.svg',  # seaTyphoon_orange
	'seatyphoon_red': 'seaTyphoon_red.svg',  # seaTyphoon_red
	'seatyphoon_yellow': 'seaTyphoon_yellow.svg',  # seaTyphoon_yellow
	'seawave_blue': 'seaWave_blue.svg',  # seaWave_blue
	'seawave_orange': 'seaWave_orange.svg',  # seaWave_orange
	'seawave_red': 'seaWave_red.svg',  # seaWave_red
	'seawave_yellow': 'seaWave_yellow.svg',  # seaWave_yellow
	'seu': 'SEU.svg',  # SEU
	'severecold_blue': 'severeCold_blue.svg',  # severeCold_blue
	'severecold_orange': 'severeCold_orange.svg',  # severeCold_orange
	'severecold_red': 'severeCold_red.svg',  # severeCold_red
	'severecold_yellow': 'severeCold_yellow.svg',  # severeCold_yellow
	'sfairlines': 'SFAirlines.svg',  # SFAirlines
	'shandongairlines': 'ShandongAirlines.svg',  # ShandongAirlines
	'shanghaiairlines': 'ShanghaiAirlines.svg',  # ShanghaiAirlines
	'shanghaikejidaxue': 'shanghaikejidaxue.svg',  # shanghaikejidaxue
	'shenzhenairlines': 'ShenzhenAirlines.svg',  # ShenzhenAirlines
	'shipinghao': 'shiPingHao.svg',  # shiPingHao
	'shiseido': 'shiseido.svg',  # shiseido
	'shmtu': 'SHMTU.svg',  # SHMTU
	'shuuemura': 'ShuUemura.svg',  # ShuUemura
	'sicau': 'SICAU.svg',  # SICAU
	'sichuanairlines': 'SichuanAirlines.svg',  # SichuanAirlines
	'sinopec': 'Sinopec.svg',  # Sinopec
	'sisley': 'Sisley.svg',  # Sisley
	'sjbank': 'SJBANK.svg',  # SJBANK
	'sjtu': 'SJTU.svg',  # SJTU
	'skii': 'skii.svg',  # skii
	'snbank': 'SNBANK.svg',  # SNBANK
	'snnu': 'SNNU.svg',  # SNNU
	'snowstorm_blue': 'snowStorm_blue.svg',  # snowStorm_blue
	'snowstorm_orange': 'snowStorm_orange.svg',  # snowStorm_orange
	'snowstorm_red': 'snowStorm_red.svg',  # snowStorm_red
	'snowstorm_yellow': 'snowStorm_yellow.svg',  # snowStorm_yellow
	'snowstrom_blue': 'snowStrom_blue.svg',  # snowStrom_blue
	'snowstrom_orange': 'snowStrom_orange.svg',  # snowStrom_orange
	'snowstrom_red': 'snowStrom_red.svg',  # snowStrom_red
	'snowstrom_yellow': 'snowStrom_yellow.svg',  # snowStrom_yellow
	'spabank': 'SPABANK.svg',  # SPABANK
	'spdb': 'SPDB.svg',  # SPDB
	'springairlines': 'SpringAirlines.svg',  # SpringAirlines
	'srbank': 'SRBANK.svg',  # SRBANK
	'stability': 'Stability.svg',  # Stability
	'starluxairlines': 'StarLuxAirlines.svg',  # StarLuxAirlines
	'stategrid': 'stateGrid.svg',  # stateGrid
	'strongconvection_blue': 'strongConvection_blue.svg',  # strongConvection_blue
	'strongconvection_orange': 'strongConvection_orange.svg',  # strongConvection_orange
	'strongconvection_red': 'strongConvection_red.svg',  # strongConvection_red
	'strongconvection_yellow': 'strongConvection_yellow.svg',  # strongConvection_yellow
	'strongcooling_blue': 'strongCooling_blue.svg',  # strongCooling_blue
	'strongcooling_orange': 'strongCooling_orange.svg',  # strongCooling_orange
	'strongcooling_red': 'strongCooling_red.svg',  # strongCooling_red
	'strongcooling_yellow': 'strongCooling_yellow.svg',  # strongCooling_yellow
	'strormsurge_blue': 'strormSurge_blue.svg',  # strormSurge_blue
	'strormsurge_orange': 'strormSurge_orange.svg',  # strormSurge_orange
	'strormsurge_red': 'strormSurge_red.svg',  # strormSurge_red
	'strormsurge_yellow': 'strormSurge_yellow.svg',  # strormSurge_yellow
	'sulwhasoo': 'sulwhasoo.svg',  # sulwhasoo
	'suno': 'Suno.svg',  # Suno
	'suparnaairlines': 'SuparnaAirlines.svg',  # SuparnaAirlines
	'svglogo': 'SVGLOGO.svg',  # SVGLOGO
	'swarovski': 'swarovski.svg',  # swarovski
	'swjtu': 'SWJTU.svg',  # SWJTU
	'swufe': 'SWUFE.svg',  # SWUFE
	'swun': 'SWUN.svg',  # SWUN
	'sxcb': 'SXCB.svg',  # SXCB
	'sxu': 'SXU.svg',  # SXU
	'sxufe': 'SXUFE.svg',  # SXUFE
	'sysu': 'SYSU.svg',  # SYSU
	'szprd': 'SZPRD.svg',  # SZPRD
	'szsbk': 'SZSBK.svg',  # SZSBK
	'sztu': 'SZTU.svg',  # SZTU
	'szu': 'SZU.svg',  # SZU
	'taccb': 'TACCB.svg',  # TACCB
	'tencent': 'Tencent.svg',  # Tencent
	'thu': 'THU.svg',  # THU
	'thundergust_blue': 'thunderGust_blue.svg',  # thunderGust_blue
	'thundergust_orange': 'thunderGust_orange.svg',  # thunderGust_orange
	'thundergust_red': 'thunderGust_red.svg',  # thunderGust_red
	'thundergust_yellow': 'thunderGust_yellow.svg',  # thunderGust_yellow
	'thunderstorm_blue': 'thunderStorm_blue.svg',  # thunderStorm_blue
	'thunderstorm_orange': 'thunderStorm_orange.svg',  # thunderStorm_orange
	'thunderstorm_red': 'thunderStorm_red.svg',  # thunderStorm_red
	'thunderstorm_yellow': 'thunderStorm_yellow.svg',  # thunderStorm_yellow
	'tianjinairlines': 'TianjinAirlines.svg',  # TianjinAirlines
	'tibetairlines': 'TibetAirlines.svg',  # TibetAirlines
	'tigerairtaiwan': 'TigerairTaiwan.svg',  # TigerairTaiwan
	'tiktok': 'Tiktok.svg',  # Tiktok
	'tju': 'TJU.svg',  # TJU
	'tlcb': 'TLCB.svg',  # TLCB
	'togetherai': 'TogetherAI.svg',  # TogetherAI
	'tomford': 'tomford.svg',  # tomford
	'tongjidaxue': 'TongJiDaXue.svg',  # TongJiDaXue
	'tonglingzhubao': 'tonglingzhubao.svg',  # tonglingzhubao
	'tornado_blue': 'tornado_blue.svg',  # tornado_blue
	'tornado_orange': 'tornado_orange.svg',  # tornado_orange
	'tornado_red': 'tornado_red.svg',  # tornado_red
	'tornado_yellow': 'tornado_yellow.svg',  # tornado_yellow
	'twitter': 'twitter.svg',  # twitter
	'typhoon_blue': 'typhoon_blue.svg',  # typhoon_blue
	'typhoon_orange': 'typhoon_orange.svg',  # typhoon_orange
	'typhoon_red': 'typhoon_red.svg',  # typhoon_red
	'typhoon_yellow': 'typhoon_yellow.svg',  # typhoon_yellow
	'tzbank': 'TZBANK.svg',  # TZBANK
	'ucas': 'UCAS.svg',  # UCAS
	'uccb': 'UCCB.svg',  # UCCB
	'uestc': 'UESTC.svg',  # UESTC
	'uibe': 'UIBE.svg',  # UIBE
	'ujn': 'UJN.svg',  # UJN
	'uniair': 'UNIAir.svg',  # UNIAir
	'unitednations': 'UnitedNations.svg',  # UnitedNations
	'unitednationsdevelopmentgoals_zh_1': 'unitedNationsDevelopmentGoals_ZH_1.svg',  # unitedNationsDevelopmentGoals_ZH_1
	'unitednationsdevelopmentgoals_zh_10': 'unitedNationsDevelopmentGoals_ZH_10.svg',  # unitedNationsDevelopmentGoals_ZH_10
	'unitednationsdevelopmentgoals_zh_11': 'unitedNationsDevelopmentGoals_ZH_11.svg',  # unitedNationsDevelopmentGoals_ZH_11
	'unitednationsdevelopmentgoals_zh_12': 'unitedNationsDevelopmentGoals_ZH_12.svg',  # unitedNationsDevelopmentGoals_ZH_12
	'unitednationsdevelopmentgoals_zh_13': 'unitedNationsDevelopmentGoals_ZH_13.svg',  # unitedNationsDevelopmentGoals_ZH_13
	'unitednationsdevelopmentgoals_zh_14': 'unitedNationsDevelopmentGoals_ZH_14.svg',  # unitedNationsDevelopmentGoals_ZH_14
	'unitednationsdevelopmentgoals_zh_15': 'unitedNationsDevelopmentGoals_ZH_15.svg',  # unitedNationsDevelopmentGoals_ZH_15
	'unitednationsdevelopmentgoals_zh_16': 'unitedNationsDevelopmentGoals_ZH_16.svg',  # unitedNationsDevelopmentGoals_ZH_16
	'unitednationsdevelopmentgoals_zh_17': 'unitedNationsDevelopmentGoals_ZH_17.svg',  # unitedNationsDevelopmentGoals_ZH_17
	'unitednationsdevelopmentgoals_zh_2': 'unitedNationsDevelopmentGoals_ZH_2.svg',  # unitedNationsDevelopmentGoals_ZH_2
	'unitednationsdevelopmentgoals_zh_3': 'unitedNationsDevelopmentGoals_ZH_3.svg',  # unitedNationsDevelopmentGoals_ZH_3
	'unitednationsdevelopmentgoals_zh_4': 'unitedNationsDevelopmentGoals_ZH_4.svg',  # unitedNationsDevelopmentGoals_ZH_4
	'unitednationsdevelopmentgoals_zh_5': 'unitedNationsDevelopmentGoals_ZH_5.svg',  # unitedNationsDevelopmentGoals_ZH_5
	'unitednationsdevelopmentgoals_zh_6': 'unitedNationsDevelopmentGoals_ZH_6.svg',  # unitedNationsDevelopmentGoals_ZH_6
	'unitednationsdevelopmentgoals_zh_7': 'unitedNationsDevelopmentGoals_ZH_7.svg',  # unitedNationsDevelopmentGoals_ZH_7
	'unitednationsdevelopmentgoals_zh_8': 'unitedNationsDevelopmentGoals_ZH_8.svg',  # unitedNationsDevelopmentGoals_ZH_8
	'unitednationsdevelopmentgoals_zh_9': 'unitedNationsDevelopmentGoals_ZH_9.svg',  # unitedNationsDevelopmentGoals_ZH_9
	'unnc': 'UNNC.svg',  # UNNC
	'upc': 'UPC.svg',  # UPC
	'urumqiair': 'UrumqiAir.svg',  # UrumqiAir
	'usst': 'USST.svg',  # USST
	'ustb': 'USTB.svg',  # USTB
	'ustc': 'USTC.svg',  # USTC
	'utibet': 'UTIBET.svg',  # UTIBET
	'vertexai': 'VertexAI.svg',  # VertexAI
	'vjshi': 'vjshi.svg',  # vjshi
	'volcengine': 'volcengine.svg',  # volcengine
	'wangyiyun-music': 'wangyiyun-music.svg',  # wangyiyun-music
	'waterlogging_blue': 'waterLogging_blue.svg',  # waterLogging_blue
	'waterlogging_orange': 'waterLogging_orange.svg',  # waterLogging_orange
	'waterlogging_red': 'waterLogging_red.svg',  # waterLogging_red
	'waterlogging_yellow': 'waterLogging_yellow.svg',  # waterLogging_yellow
	'weibo': 'weiBo.svg',  # weiBo
	'weixin': 'weiXin.svg',  # weiXin
	'weixinpay': 'weixinpay.svg',  # weixinpay
	'westair': 'WestAir.svg',  # WestAir
	'wfccb': 'WFCCB.svg',  # WFCCB
	'whbank': 'WHBANK.svg',  # WHBANK
	'whccb': 'WHCCB.svg',  # WHCCB
	'whoo': 'whoo.svg',  # whoo
	'whu': 'WHU.svg',  # WHU
	'wildfire_blue': 'wildFire_blue.svg',  # wildFire_blue
	'wildfire_orange': 'wildFire_orange.svg',  # wildFire_orange
	'wildfire_red': 'wildFire_red.svg',  # wildFire_red
	'wildfire_yellow': 'wildFire_yellow.svg',  # wildFire_yellow
	'wireicing_blue': 'wireIcing_blue.svg',  # wireIcing_blue
	'wireicing_orange': 'wireIcing_orange.svg',  # wireIcing_orange
	'wireicing_red': 'wireIcing_red.svg',  # wireIcing_red
	'wireicing_yellow': 'wireIcing_yellow.svg',  # wireIcing_yellow
	'word': 'word.svg',  # word
	'wuliangye': 'Wuliangye.svg',  # Wuliangye
	'wust': 'WUST.svg',  # WUST
	'wut': 'WUT.svg',  # WUT
	'wzbank': 'WZBANK.svg',  # WZBANK
	'xabank': 'XABANK.svg',  # XABANK
	'xdu': 'XDU.svg',  # XDU
	'xet': 'XET.svg',  # XET
	'xiamenair': 'XiamenAir.svg',  # XiamenAir
	'xiaohongshu': 'xiaoHongShu.svg',  # xiaoHongShu
	'xiaomi': 'xiaomi.svg',  # xiaomi
	'xiaoyuzhou': 'xiaoYuZhou.svg',  # xiaoYuZhou
	'xieruilin': 'xieruilin.svg',  # xieruilin
	'xiguashiping': 'xiGuaShiPing.svg',  # xiGuaShiPing
	'ximalaya': 'xiMaLaYa.svg',  # xiMaLaYa
	'xinzhi': 'xinzhi.svg',  # xinzhi
	'xjb': 'XJB.svg',  # XJB
	'xjhb': 'XJHB.svg',  # XJHB
	'xjtu': 'XJTU.svg',  # XJTU
	'xju': 'XJU.svg',  # XJU
	'xmbank': 'XMBANK.svg',  # XMBANK
	'xmintb': 'XMINTB.svg',  # XMINTB
	'xmu': 'XMU.svg',  # XMU
	'xtb': 'XTB.svg',  # XTB
	'yaccb': 'YACCB.svg',  # YACCB
	'ybccb': 'YBCCB.svg',  # YBCCB
	'ykyhb': 'YKYHB.svg',  # YKYHB
	'yndm': 'yndm.svg',  # yndm
	'ynhtbank': 'YNHTBANK.svg',  # YNHTBANK
	'ynu': 'YNU.svg',  # YNU
	'youku': 'youku.svg',  # youku
	'yqccb': 'YQCCB.svg',  # YQCCB
	'ysl': 'ysl.svg',  # ysl
	'ytb': 'YTB.svg',  # YTB
	'yuebao': 'yuebao.svg',  # yuebao
	'yuxi': 'yuxi.svg',  # yuxi
	'zengzhangchaoren': 'zengzhangchaoren.svg',  # zengzhangchaoren
	'zgbank': 'ZGBANK.svg',  # ZGBANK
	'zhenzhenligong': 'zhenzhenligong.svg',  # zhenzhenligong
	'zhi': 'zhi.svg',  # zhi
	'zhifubao': 'zhifubao.svg',  # zhifubao
	'zhimaxinyong': 'zhimaxinyong.svg',  # zhimaxinyong
	'zhipu': 'Zhipu.svg',  # Zhipu
	'zhishixingqiu': 'zhiShiXingQiu.svg',  # zhiShiXingQiu
	'zhongfuzhubao': 'zhongfuzhubao.svg',  # zhongfuzhubao
	'zhongguozhubao': 'zhongguozhubao.svg',  # zhongguozhubao
	'zhongyangxijuxueyuan_wordmark': 'ZhongYangXiJuXueYuan_wordmark.svg',  # ZhongYangXiJuXueYuan_wordmark
	'zhoudafu': 'zhoudafu.svg',  # zhoudafu
	'zhoudafuzhuangcheng': 'zhoudafuzhuangcheng.svg',  # zhoudafuzhuangcheng
	'zhoudasheng': 'zhoudasheng.svg',  # zhoudasheng
	'zhoushengsheng': 'zhoushengsheng.svg',  # zhoushengsheng
	'zhubai': 'zhuBai.svg',  # zhuBai
	'zjkccb': 'ZJKCCB.svg',  # ZJKCCB
	'zju': 'ZJU.svg',  # ZJU
	'zjut': 'ZJUT.svg',  # ZJUT
	'zybank': 'ZYBANK.svg',  # ZYBANK
	'zzb': 'ZZB.svg',  # ZZB
	'zzbank': 'ZZBANK.svg',  # ZZBANK
	'zzu': 'ZZU.svg',  # ZZU
}

__all__ = ['PREDEFINED_ICONS']
