#!/usr/bin/env bash
# cortex/scripts/install_wrappers.sh
#
# Generates the proxy wrappers under <target-dir> (default ~/.cortex/scripts/).
# Wrappers embed the absolute marketplace path so the user-facing entry points
# stay stable across plugin upgrades.
#
# Wrappers (11 total):
#   - cron/proxy: lint.sh (dual-mode), fold.sh, dashboard.sh, install_cron.sh, config.sh, update.sh
#   - skill entrypoints: doctor.sh, ingest.sh, search.sh, save.sh, refactor.sh
#
# Usage:
#   bash install_wrappers.sh --install-path <abs cortex root> [--target-dir <dir>] [--no-overwrite]
#
# Exit codes:
#   0  success
#   2  bad args
#   3  install-path missing or not a directory

set -euo pipefail

if [[ -t 2 && -z "${NO_COLOR:-}" ]]; then
  _C_RESET=$'\033[0m'; _C_BOLD=$'\033[1m'; _C_DIM=$'\033[2m'
  _C_GREEN=$'\033[32m'; _C_CYAN=$'\033[36m'
else
  _C_RESET=""; _C_BOLD=""; _C_DIM=""; _C_GREEN=""; _C_CYAN=""
fi

print_help() {
  cat <<'EOF'
install_wrappers.sh — generate ~/.cortex/scripts/*.sh wrappers

USAGE:
  bash install_wrappers.sh --install-path <abs> [--target-dir <dir>] [--no-overwrite]

OPTIONS:
  --install-path <abs>   absolute marketplace cortex root (required)
  --target-dir <dir>     destination dir (default: ~/.cortex/scripts)
  --no-overwrite         skip wrappers that already exist
  --help, -h             this help
EOF
}

INSTALL_PATH=""
TARGET_DIR="$HOME/.cortex/scripts"
NO_OVERWRITE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-path) INSTALL_PATH="${2:-}"; shift 2 ;;
    --install-path=*) INSTALL_PATH="${1#*=}"; shift ;;
    --target-dir) TARGET_DIR="${2:-}"; shift 2 ;;
    --target-dir=*) TARGET_DIR="${1#*=}"; shift ;;
    --no-overwrite) NO_OVERWRITE=1; shift ;;
    -h|--help) print_help; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$INSTALL_PATH" ]]; then
  echo "[install_wrappers.sh] --install-path is required" >&2
  exit 2
fi
if [[ ! -d "$INSTALL_PATH" ]]; then
  echo "[install_wrappers.sh] --install-path is not a directory: $INSTALL_PATH" >&2
  exit 3
fi

mkdir -p "$TARGET_DIR"
GENERATED_AT="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

# Emit one wrapper. $1 = filename, $2 = body (single command line after `exec`
# or, for update.sh, a multi-line block).
emit() {
  local name="$1"; shift
  local body="$1"; shift
  local dest="$TARGET_DIR/$name"
  if [[ -e "$dest" && "$NO_OVERWRITE" == "1" ]]; then
    echo "[install_wrappers.sh] skipped (exists): $dest" >&2
    return 0
  fi
  if [[ -e "$dest" ]]; then
    echo "[install_wrappers.sh] regenerated: $dest" >&2
  fi
  {
    printf '#!/usr/bin/env bash\n'
    printf '# generated by cortex install on %s; do not edit by hand\n' "$GENERATED_AT"
    printf 'set -euo pipefail\n'
    printf '%s\n' "$body"
  } > "$dest"
  chmod +x "$dest"
}

# `exec` keeps a single PID and forwards signals correctly.
emit_exec() {
  emit "$1" "exec $2 \"\$@\""
}

emit_exec fold.sh           "bash \"$INSTALL_PATH/scripts/cron/fold.sh\""
emit_exec dashboard.sh      "bash \"$INSTALL_PATH/scripts/cron/dashboard.sh\""
emit_exec install_cron.sh   "bash \"$INSTALL_PATH/scripts/install_cron.sh\""
emit_exec config.sh         "python3 \"$INSTALL_PATH/scripts/cortex_config.py\""

# doctor: cortex-doctor is a Claude Code skill. Slash commands don't work in
# headless `-p` mode, so we inject SKILL.md via --append-system-prompt and pass
# a plain task description. --bare skips hooks/plugins/MCP for a clean run.
emit doctor.sh "$(cat <<EOB
SKILL_PATH="$INSTALL_PATH/skills/cortex-doctor/SKILL.md"
if [[ ! -f "\$SKILL_PATH" ]]; then
  echo "cortex-doctor SKILL.md missing: \$SKILL_PATH" >&2
  exit 1
fi
LIB_PATH="$INSTALL_PATH/scripts/lib/stream_progress.sh"
if [[ ! -f "\$LIB_PATH" ]]; then
  echo "stream_progress.sh missing: \$LIB_PATH" >&2
  exit 1
fi
# shellcheck source=../../plugins/tools/cortex/scripts/lib/stream_progress.sh
source "\$LIB_PATH"
export CORTEX_JOB_LABEL="cortex-doctor"
# trap Ctrl-C: stream_progress handles heartbeat cleanup internally.
cortex_stream_runner claude --bare -p \\
  --append-system-prompt "\$(cat "\$SKILL_PATH")" \\
  "运行 cortex 健康检查 (cortex-doctor skill), 报告 vault/config/links/dead-links 等问题, 输出可读结果" "\$@"
EOB
)"

# lint.sh: dual-mode wrapper.
#   - no flag (or any args without --fix): cron mode, exec cron/lint.sh (JSON output, read-only).
#   - --fix: interactive fix mode via cortex-lint skill (AskUserQuestion flow).
emit lint.sh "$(cat <<EOB
if [[ "\${1:-}" == "--fix" ]]; then
  shift
  SKILL_PATH="$INSTALL_PATH/skills/cortex-lint/SKILL.md"
  if [[ ! -f "\$SKILL_PATH" ]]; then
    echo "cortex-lint SKILL.md missing: \$SKILL_PATH" >&2
    exit 1
  fi
  LIB_PATH="$INSTALL_PATH/scripts/lib/stream_progress.sh"
  if [[ ! -f "\$LIB_PATH" ]]; then
    echo "stream_progress.sh missing: \$LIB_PATH" >&2
    exit 1
  fi
  # shellcheck source=../../plugins/tools/cortex/scripts/lib/stream_progress.sh
  source "\$LIB_PATH"
  export CORTEX_JOB_LABEL="cortex-lint-fix"
  cortex_stream_runner claude --bare -p \\
    --append-system-prompt "\$(cat "\$SKILL_PATH")" \\
    "对 cortex vault 跑 lint 并 --fix 交互修复. 按 cortex-lint skill 工作流: 跑 run.py 获 JSON 报告 → 解析 errors[] → vault-structure-violation 各项用 AskUserQuestion 工具询问 (move/delete/whitelist/skip), 其它 autofix 项直接落. \$*" "\$@"
else
  exec bash "$INSTALL_PATH/scripts/cron/lint.sh" "\$@"
fi
EOB
)"

# ingest.sh: cortex-ingest skill — auto-detect url/file/git/dir source.
emit ingest.sh "$(cat <<EOB
SKILL_PATH="$INSTALL_PATH/skills/cortex-ingest/SKILL.md"
if [[ ! -f "\$SKILL_PATH" ]]; then
  echo "cortex-ingest SKILL.md missing: \$SKILL_PATH" >&2
  exit 1
fi
LIB_PATH="$INSTALL_PATH/scripts/lib/stream_progress.sh"
if [[ ! -f "\$LIB_PATH" ]]; then
  echo "stream_progress.sh missing: \$LIB_PATH" >&2
  exit 1
fi
# shellcheck source=../../plugins/tools/cortex/scripts/lib/stream_progress.sh
source "\$LIB_PATH"
export CORTEX_JOB_LABEL="cortex-ingest"
cortex_stream_runner claude --bare -p \\
  --append-system-prompt "\$(cat "\$SKILL_PATH")" \\
  "摄取以下源到 cortex vault. 源: \$* (自动判断 url/file/git/dir). 按 cortex-ingest skill 流程: url_security → fetch/read → html_sanitize → masking → save." "\$@"
EOB
)"

# search.sh: cortex-search skill — multi-tier fallback search.
emit search.sh "$(cat <<EOB
SKILL_PATH="$INSTALL_PATH/skills/cortex-search/SKILL.md"
if [[ ! -f "\$SKILL_PATH" ]]; then
  echo "cortex-search SKILL.md missing: \$SKILL_PATH" >&2
  exit 1
fi
LIB_PATH="$INSTALL_PATH/scripts/lib/stream_progress.sh"
if [[ ! -f "\$LIB_PATH" ]]; then
  echo "stream_progress.sh missing: \$LIB_PATH" >&2
  exit 1
fi
# shellcheck source=../../plugins/tools/cortex/scripts/lib/stream_progress.sh
source "\$LIB_PATH"
export CORTEX_JOB_LABEL="cortex-search"
cortex_stream_runner claude --bare -p \\
  --append-system-prompt "\$(cat "\$SKILL_PATH")" \\
  "在 cortex vault 搜索: \$*. 按 cortex-search skill 多级回退 (hot → index → SC → rg → MCP). 引用页路径 + 片段." "\$@"
EOB
)"

# save.sh: cortex-save skill — body from stdin, kind/title from args.
emit save.sh "$(cat <<EOB
SKILL_PATH="$INSTALL_PATH/skills/cortex-save/SKILL.md"
if [[ ! -f "\$SKILL_PATH" ]]; then
  echo "cortex-save SKILL.md missing: \$SKILL_PATH" >&2
  exit 1
fi
LIB_PATH="$INSTALL_PATH/scripts/lib/stream_progress.sh"
if [[ ! -f "\$LIB_PATH" ]]; then
  echo "stream_progress.sh missing: \$LIB_PATH" >&2
  exit 1
fi
# shellcheck source=../../plugins/tools/cortex/scripts/lib/stream_progress.sh
source "\$LIB_PATH"
export CORTEX_JOB_LABEL="cortex-save"
KIND="\${1:-log}"
TITLE="\${2:-quick save}"
BODY="\$(cat)"
cortex_stream_runner claude --bare -p \\
  --append-system-prompt "\$(cat "\$SKILL_PATH")" \\
  "落档到 cortex vault: kind=\$KIND, title=\$TITLE. body 如下 (经 masking 后写盘):

\$BODY"
EOB
)"

# refactor.sh: cortex-refactor skill — dry-run default; --apply to persist.
emit refactor.sh "$(cat <<EOB
SKILL_PATH="$INSTALL_PATH/skills/cortex-refactor/SKILL.md"
if [[ ! -f "\$SKILL_PATH" ]]; then
  echo "cortex-refactor SKILL.md missing: \$SKILL_PATH" >&2
  exit 1
fi
LIB_PATH="$INSTALL_PATH/scripts/lib/stream_progress.sh"
if [[ ! -f "\$LIB_PATH" ]]; then
  echo "stream_progress.sh missing: \$LIB_PATH" >&2
  exit 1
fi
# shellcheck source=../../plugins/tools/cortex/scripts/lib/stream_progress.sh
source "\$LIB_PATH"
export CORTEX_JOB_LABEL="cortex-refactor"
cortex_stream_runner claude --bare -p \\
  --append-system-prompt "\$(cat "\$SKILL_PATH")" \\
  "执行 cortex-refactor 子命令: \$*. dry-run 默认; --apply 才落. 子命令: rename / merge / split / fold / migrate-locale / restructure / dedupe / extract / inline / graph-rebalance." "\$@"
EOB
)"

# update.sh: two commands cannot share a single `exec`, chain with `&&`.
emit update.sh "$(cat <<'EOB'
claude plugins marketplace update ccplugin-market \
  && claude plugins update cortex@ccplugin-market
EOB
)"

printf '%s[install_wrappers.sh]%s %s✓%s wrote %s11 wrappers%s to %s%s%s\n' \
  "$_C_CYAN" "$_C_RESET" "$_C_GREEN" "$_C_RESET" \
  "$_C_BOLD" "$_C_RESET" "$_C_BOLD" "$TARGET_DIR" "$_C_RESET" >&2
